stages:
  get-features:
    cmd: python3 scripts/get_features.py  twitter_data.csv
    deps:
    - twitter_data.csv
    - scripts/get_features.py
    outs:
    - datasets/stage1
  data_preprocessing:
    cmd: python3 scripts/data_preprocessing.py  datasets/stage1/train.csv
    deps:
    - datasets/stage1/train.csv 
    - scripts/data_prepocessing.py
    outs:
    - datasets/stage2
  data_split:
    cmd: python3 scripts/split.py datasets/stage2/train.csv  
    deps:
    - datasets/stage2/train.csv 
    - scripts/split.py
    outs:
    - datasets/stage3
  train:
    cmd: python3 scripts/model.py datasets/stage3/train.csv 
    deps:
    - datasets/stage3/train.csv 
    - scripts/model.py
    outs:
    - model/model.pkl